#!/bin/bash

# This script will copy my (and may be even yours) environment to remote host.

PROGNAME=$(basename $0)
AKEYS_FILE="~/.ssh/authorized_keys"
AKEYS_COPY="NO"

print_usage() {
  echo "Usage: $PROGNAME [-A] user@hostname ..."
  echo "  -A enables authorized_keys copy (with overwrite), default: $AKEYS_COPY"
}


while getopts "hA" option; do
  case $option in
    h)
      print_usage
      exit 0
      ;;
    A)
      AKEYS_COPY="YES"
      AKEYS_CONTENT=$(cat $AKEY_FILE)
      ;;
    ?)
      print_usage
      exit 2
      ;;
  esac
done
shift $(($OPTIND - 1))

if [ -z "$*" ]; then
  echo "Specify at least one hostname."
  exit 2
fi

cd ~

for HOSTNAME in $*; do
  host=`echo $HOSTNAME | cut -f1 -d':'`
  port=`echo $HOSTNAME | cut -f2 -d':' -s`
  if [ -z $port ]; then
    port="22"
  fi
  
  if [ -z $host ]; then
    echo "No host was found in '$HOSTNAME'!"
    exit 2
  fi

  echo "Copying files to $HOSTNAME..."

  if [ "x$AKEYS_COPY" = "xYES" ]; then
    echo "Copying $AKEYS_FILE..."

    if [ $? -eq 0 -a ! -z "$AKEYS_CONTENT" ]; then
      ssh -p $port $host "mkdir -p ~/.ssh; chmod 700 .ssh; echo " $AKEYS_CONTENT " > $AKEYS_FILE; chmod 600 $AKEYS_FILE"
    else
      echo "$AKEYS_PATH wasn't copied - it is empty or unreadable. Skipping..."
    fi
  fi

  for i in bin .config .vimrc .tmux.conf .screenrc .profile .bashrc .gitconfig .hgrc .zshrc .zsh; do
    if [ -r $i ];then
      scp -q -C -P $port -r "$i" $host:
    fi
  done

done
