#!/bin/bash

set -e

FOTKI=asd@mokote.com:/mokote/sites/nearbird.ru/site/fotki
PUBLIC="http://nearbird.ru/fotki"

fpath=$1
filename=$(basename $fpath)
extension=${filename##*.}
filename=${filename%.*}
hash=`md5 -q $1`

scp -q ${fpath} ${FOTKI}/${hash}.${extension}
echo ${PUBLIC}/${hash}.${extension}
