#!/bin/bash

set -e

FOTKI=asd@mokote.com:/mokote/sites/nearbird.ru/site/fotki
PUBLIC="http://nearbird.ru/fotki"

fpath=$1
filename=$(basename $fpath)
extension=$(echo ${filename##*.} | tr '[A-Z]' '[a-z]')
filename=${filename%.*}
hash=`md5 -q $1`

folder=$2
if [ "x${folder}" != "x" ]; then
    folder="/${folder}"
fi

scp -q ${fpath} ${FOTKI}${folder}/${hash}.${extension}
echo ${PUBLIC}${folder}/${hash}.${extension}
